import { BarChart3 } from "lucide-react";
import { useMemo } from "react";
import type { SavedEntry } from "@/features/library/types";
import type { OptimizationEvent } from "@/features/prompt-optimizer/types";

export default function WeeklySavingsReport({ history, library }: { history: OptimizationEvent[]; library: SavedEntry[] }) {
  const report = useMemo(() => {
    const start = new Date(); start.setDate(start.getDate() - 6); start.setHours(0, 0, 0, 0);
    const days = Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - (6 - index)); return date.toISOString().slice(0, 10); });
    const dailyMap = new Map(days.map((day) => [day, { day, count: 0, tokens: 0, krw: 0 }]));
    const tagCounts = new Map<string, number>(); const recent: OptimizationEvent[] = []; let savingsTokens = 0; let savingsKrw = 0;
    history.forEach((item) => { if (new Date(item.at) < start) return; recent.push(item); savingsTokens += item.savingsTokens; savingsKrw += item.savingsKrw; item.tags.forEach((tag) => tagCounts.set(tag, (tagCounts.get(tag) || 0) + 1)); const bucket = dailyMap.get(item.at.slice(0, 10)); if (bucket) { bucket.count += 1; bucket.tokens += item.savingsTokens; bucket.krw += item.savingsKrw; } });
    library.forEach((item) => { if (new Date(item.savedAt) >= start) item.tags.forEach((tag) => tagCounts.set(tag, (tagCounts.get(tag) || 0) + 1)); });
    const topTags = Array.from(tagCounts.entries()).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0], "ko")).slice(0, 5);
    const daily = days.map((day) => dailyMap.get(day)!);
    return { recent, topTags, savingsTokens, savingsKrw, daily, maxDailyTokens: Math.max(1, ...daily.map((item) => item.tokens)), maxTagCount: Math.max(1, ...topTags.map(([, count]) => count)) };
  }, [history, library]);
  const { recent, topTags, savingsTokens, savingsKrw, daily, maxDailyTokens, maxTagCount } = report;
  return <div className="editor-card mobile-deferred p-6 md:p-7"><div className="flex items-start justify-between gap-4"><div><div className="section-kicker"><span className="counter">08</span> WEEKLY REPORT</div><h2 className="mt-3 font-serif text-2xl font-bold tracking-[-0.04em]">이번 주 태그·비용 절감</h2></div><div className="flex h-8 w-8 items-center justify-center border border-[#1C1D21]/15 bg-white text-[#2563EB]"><BarChart3 size={15} /></div></div><p className="mt-2 text-[12px] leading-5 text-[#66686C]">최근 7일의 저장 프롬프트와 성공한 CheapAI 추천 이력을 열 때마다 자동 집계합니다.</p>{recent.length || topTags.length ? <><div className="weekly-hero mt-5"><span className="font-mono text-[9px] tracking-[0.12em] opacity-75">THIS WEEK SAVED</span><strong>{savingsTokens.toLocaleString()}<em> tok</em></strong><div><span>예상 ₩{savingsKrw.toFixed(2)}</span><span>·</span><span>CheapAI {recent.length}회</span></div></div><div className="mt-3 grid grid-cols-2 gap-2"><div className="analytics-metric"><strong>{recent.length}</strong><span>CheapAI 분석</span></div><div className="analytics-metric"><strong>{topTags.length}</strong><span>활성 태그</span></div></div><div className="mt-4 border border-[#1C1D21]/10 bg-white/75 p-3"><div className="flex items-center justify-between"><span className="font-mono text-[10px] font-semibold tracking-[0.08em]">일별 절감 토큰</span><span className="font-mono text-[9px] text-[#2563EB]">최근 7일</span></div><div className="weekly-chart mt-3" role="img" aria-label="최근 7일 CheapAI 일별 절감 토큰 차트">{daily.map((item) => <div key={item.day} className="weekly-bar"><span className="weekly-bar-value">{item.tokens || "–"}</span><div className="weekly-bar-track"><span className="weekly-bar-fill" style={{ height: `${Math.max(item.tokens ? 12 : 0, (item.tokens / maxDailyTokens) * 100)}%` }} /></div><span className="weekly-bar-label">{item.day.slice(5).replace("-", "/")}</span></div>)}</div><p className="mt-2 font-mono text-[9px] text-[#77797C]">막대를 누적한 값입니다. AI 추천을 성공적으로 실행한 날만 반영됩니다.</p></div><div className="mt-3 border border-[#1C1D21]/10 bg-white/75 p-3"><div className="flex items-center justify-between"><span className="font-mono text-[10px] font-semibold tracking-[0.08em]">가장 많이 사용된 태그</span><span className="font-mono text-[9px] text-[#77797C]">저장·AI 이력 합산</span></div><div className="mt-3 space-y-2">{topTags.map(([tag, count]) => <div key={tag} className="flex items-center gap-2"><span className="w-20 truncate font-mono text-[9px] text-[#4E5055]">#{tag}</span><span className="h-2 flex-1 overflow-hidden bg-[#E7E2D9]"><span className="block h-full bg-[#2563EB]" style={{ width: `${(count / maxTagCount) * 100}%` }} /></span><span className="w-6 text-right font-mono text-[9px] text-[#77797C]">{count}</span></div>)}</div></div></> : <div className="mt-5 border border-dashed border-[#1C1D21]/15 bg-[#F0ECE4] px-4 py-5 font-mono text-[10px] leading-5 text-[#77797C]">CheapAI 추천을 실행하거나 태그를 붙여 프롬프트를 저장하면 이번 주 리포트가 자동으로 채워집니다.</div>}</div>;
}
