import { Cloud, DatabaseBackup, Download, FileUp, KeyRound, Loader2, Plus, Settings2, Sparkles, Tag, X } from "lucide-react";
import type { BackupPreview, ConflictDecision } from "@/features/library/types";
import type { AiMode, AiModel } from "@/features/prompt-optimizer/types";

type AssistantToolsProps = {
  aiMode: AiMode; setAiMode: (mode: AiMode) => void; aiModel: AiModel; setAiModel: (model: AiModel) => void;
  cheapAiKey: string; updateCheapAiKey: (value: string) => void; isSuggesting: boolean; requestAiTags: () => void;
  customTags: string[]; customTagInput: string; setCustomTagInput: (value: string) => void; addCustomTag: () => void; removeCustomTag: (tag: string) => void;
  exportBackup: () => void; prepareBackupImport: (file: File | undefined) => void; backupPreview: BackupPreview | null; backupMode: "merge" | "replace"; setBackupMode: (mode: "merge" | "replace") => void; backupSelected: string[]; setBackupSelected: (ids: string[]) => void; applyBackupImport: () => void;
  estimatedInputTokens: number; estimatedOutputTokens: number; estimatedKrw: number;
};

export default function AssistantToolsPanel(props: AssistantToolsProps) {
  const { aiMode, setAiMode, aiModel, setAiModel, cheapAiKey, updateCheapAiKey, isSuggesting, requestAiTags, customTags, customTagInput, setCustomTagInput, addCustomTag, removeCustomTag, exportBackup, prepareBackupImport, backupPreview, backupMode, setBackupMode, backupSelected, setBackupSelected, applyBackupImport, estimatedInputTokens, estimatedOutputTokens, estimatedKrw } = props;
  return <div className="editor-card p-6 md:p-7"><div className="flex items-start justify-between gap-4"><div><div className="section-kicker"><span className="counter">04</span> AI & DATA TOOLS</div><h2 className="mt-3 font-serif text-2xl font-bold tracking-[-0.04em]">추천 · 백업 · 태그 사전</h2></div><div className="flex h-8 w-8 items-center justify-center border border-[#1C1D21]/15 bg-white text-[#2563EB]"><Settings2 size={15} /></div></div>
    <div className="mt-5 border border-[#1C1D21]/10 bg-white/75 p-3"><div className="flex items-center gap-2"><Cloud size={14} className="text-[#2563EB]" /><span className="font-mono text-[10px] font-semibold tracking-[0.08em]">태그 추천 모드</span></div><div className="mt-3 grid grid-cols-2 border border-[#1C1D21]/15 p-1"><button onClick={() => setAiMode("local")} className={`px-2 py-2 font-mono text-[9px] transition ${aiMode === "local" ? "bg-[#1C1D21] text-white" : "text-[#67696C]"}`}>로컬 분석</button><button onClick={() => setAiMode("cheapai")} className={`px-2 py-2 font-mono text-[9px] transition ${aiMode === "cheapai" ? "bg-[#2563EB] text-white" : "text-[#67696C]"}`}>CheapAI 모델</button></div>{aiMode === "local" ? <p className="mt-3 font-mono text-[9px] leading-5 text-[#74767A]">입력을 브라우저 안에서 분석합니다. 외부 전송과 API 키가 필요 없습니다.</p> : <div className="mt-3 space-y-2"><select value={aiModel} onChange={(event) => setAiModel(event.target.value as AiModel)} className="field-input h-9 py-1.5 font-mono text-[10px]"><option value="gpt-5.6-sol">ChatGPT · GPT-5.6 Sol</option><option value="claude-sonnet-5">Claude · Sonnet 5</option></select><div className="grid grid-cols-3 gap-px border border-[#2563EB]/20 bg-[#2563EB]/20 font-mono text-[9px]"><span className="bg-[#EFF4FF] px-2 py-2 text-[#3564B9]">입력 약 {estimatedInputTokens} tok</span><span className="bg-[#EFF4FF] px-2 py-2 text-[#3564B9]">출력 최대 {estimatedOutputTokens} tok</span><span className="bg-[#EFF4FF] px-2 py-2 font-semibold text-[#1D4ED8]">예상 ₩{estimatedKrw.toFixed(2)} · {Math.ceil(estimatedKrw * 10)} cr</span></div><div className="flex items-center gap-2 border border-[#1C1D21]/15 bg-white px-3"><KeyRound size={13} className="shrink-0 text-[#2563EB]" /><input type="password" value={cheapAiKey} onChange={(event) => updateCheapAiKey(event.target.value)} placeholder="csk_... API 키 (이 브라우저에만 저장)" className="h-9 min-w-0 flex-1 bg-transparent font-mono text-[10px] outline-none placeholder:text-[#999B9E]" /></div><button onClick={requestAiTags} disabled={isSuggesting} className="flex w-full items-center justify-center gap-2 bg-[#2563EB] px-3 py-2.5 font-mono text-[10px] font-semibold text-white transition hover:bg-[#1D4ED8] disabled:cursor-not-allowed disabled:opacity-60">{isSuggesting ? <Loader2 size={13} className="animate-spin" /> : <Sparkles size={13} />} {isSuggesting ? "AI가 태그 분석 중" : "AI로 태그 다시 추천"}</button><p className="font-mono text-[9px] leading-5 text-[#77797D]">예상 비용은 현재 입력과 최대 출력량 기준이며 실제 차감은 응답 usage 기준입니다.</p></div>}</div>
    <div className="mt-3 border border-[#1C1D21]/10 bg-white/75 p-3"><div className="flex items-center gap-2"><DatabaseBackup size={14} className="text-[#2563EB]" /><span className="font-mono text-[10px] font-semibold tracking-[0.08em]">JSON 백업 · 복원</span></div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={exportBackup} className="tool-button"><Download size={13} /> 내보내기</button><label className="tool-button"><FileUp size={13} /> 비교 후 가져오기<input type="file" accept="application/json,.json" className="sr-only" onChange={(event) => { void prepareBackupImport(event.target.files?.[0]); event.currentTarget.value = ""; }} /></label></div>{backupPreview ? <div className="mt-3 border border-[#2563EB]/20 bg-[#EFF4FF]/55 p-2.5"><p className="font-mono text-[9px] font-semibold text-[#3564B9]">{backupPreview.fileName} · 신규 {backupPreview.newCount} · 변경 {backupPreview.updateCount} · 동일 {backupPreview.sameCount}</p><div className="mt-2 grid grid-cols-2 border border-[#1C1D21]/15 p-1"><button onClick={() => setBackupMode("merge")} className={`px-2 py-1.5 font-mono text-[9px] ${backupMode === "merge" ? "bg-[#1C1D21] text-white" : "text-[#66686C]"}`}>기존과 병합</button><button onClick={() => setBackupMode("replace")} className={`px-2 py-1.5 font-mono text-[9px] ${backupMode === "replace" ? "bg-[#1C1D21] text-white" : "text-[#66686C]"}`}>선택 항목 교체</button></div><div className="mt-2 max-h-24 space-y-1 overflow-auto">{backupPreview.library.map((entry) => <label key={entry.id} className="flex items-center gap-2 font-mono text-[9px] text-[#55575B]"><input type="checkbox" checked={backupSelected.includes(entry.id)} onChange={() => setBackupSelected(backupSelected.includes(entry.id) ? backupSelected.filter((id) => id !== entry.id) : [...backupSelected, entry.id])} />{entry.kind === "profile" ? "프로필" : "설정"} · {entry.name}</label>)}</div><button onClick={applyBackupImport} className="mt-2 w-full bg-[#2563EB] px-2 py-2 font-mono text-[9px] font-semibold text-white">선택 {backupSelected.length}개 적용</button></div> : <p className="mt-2 font-mono text-[9px] leading-5 text-[#77797D]">파일을 선택하면 신규·변경·동일 항목을 비교하고 복원 방식을 고를 수 있습니다.</p>}</div>
    <div className="mt-3 border border-[#1C1D21]/10 bg-white/75 p-3"><div className="flex items-center gap-2"><Tag size={14} className="text-[#2563EB]" /><span className="font-mono text-[10px] font-semibold tracking-[0.08em]">사용자 정의 태그 사전</span></div><div className="mt-3 flex gap-2"><input value={customTagInput} onChange={(event) => setCustomTagInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") addCustomTag(); }} placeholder="예: 월간보고, 신제품" className="field-input h-9 min-w-0 flex-1 py-1.5 text-[11px]" /><button onClick={addCustomTag} className="inline-flex h-9 items-center gap-1 bg-[#1C1D21] px-3 font-mono text-[10px] font-semibold text-white transition hover:bg-[#2563EB]"><Plus size={13} /> 등록</button></div><div className="mt-3 flex flex-wrap gap-1.5">{customTags.length ? customTags.map((tag) => <span key={tag} className="dictionary-tag">#{tag}<button onClick={() => removeCustomTag(tag)} aria-label={`${tag} 삭제`}><X size={10} /></button></span>) : <span className="font-mono text-[9px] text-[#838589]">등록한 태그는 검색·필터·추천에 함께 반영됩니다.</span>}</div></div>
  </div>;
}
